# Name of workflow
name: 

# Controls when the action will run. 
on:
  # Triggers the workflow on push tag that match mask v*.*.*
  push:
    tags:
      - 'v*-*-*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Put tag name into variable         
      - name: Set tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

#      # Deploy to Google App Engine     
#      - name: Deploy to App Engine
#        uses: google-github-actions/deploy-appengine@v0.2.0
#        with:
#          deliverables: app.yaml
#          project_id: ${{ secrets.GCP_PROJECT }}
#          credentials: ${{ secrets.GCP_SA_KEY }}
#          promote: true
#          version: ${{ env.RELEASE_VERSION }}    

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJECT }} --quiet --promote --version ${{ env.RELEASE_VERSION }} --stop-previous-version
