# Name of workflow
name: Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on Pull Request to master branch
  pull_request:
    branches:
      - master 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: .*
          DEFAULT_BUMP: patch

      # Replace dots with dashes, since App Engine doesn't support dots in the version names
      - name: Get release version name from latest tag
        run: echo "RELEASE_VERSION=$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)" | sed 's/\./-/g' >> $GITHUB_ENV

      # Setup gcloud utils
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Copy app.yaml from bucket
      - name: Dowload app.yaml from Google Storage
        run: gsutil cp ${{ secrets.GCP_BUCKET }}/app.yaml app.yaml

      # Deploy App in dry-run mode
      - name: Deploy release vesrion
        run: gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJECT }} --quiet --no-promote --version rc-${{ env.RELEASE_VERSION }}

      # Adds comment with URL of release app to a pull request
      - name: Add URL to PR comment
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            *** Release URL: https://rc-${{ env.RELEASE_VERSION }}-dot-${{ secrets.GCP_PROJECT }}.appspot.com/ ***
          allow-repeats: true
